### ISSUE TITLE
header

### ISSUE THREAD

**Issue by markendley** [markendley/ftrnghp#9]
Can you please make the email address and phone number bigger on desktop? Pretty hard to read at the moment. And please use the icons in the psd.
This client will notice for sure.

and Just a little more space between these icons in the nav please
![screen shot 2018-03-26 at 1 49 03 pm](https://user-images.githubusercontent.com/6570606/37902242-8cc6041c-313f-11e8-82a6-e19b1d7611ec.png)

**Comment by ugurcanbulut** [comment]
First of all, to be honest, the difference is barely noticeable. Secondly, I didn't use different icons just for fun. Vector smart object links are broken in PSD file so if I will use them, they have to be png instead of svg. Lastly, the client (fostering hope) doesn't have a YouTube link on the current web site but she has Linkedin link. 

In sum; I can use the ones from psd without any problem but I may need an icon for Linkedin and the original svg/ai/eps version of all the icons - if he wants a pixel perfect quality - as you know.

**Comment by markendley** [comment]
its cool, I'll deal with this guy
